version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    ports:
      - 9200:9200
    volumes:
      - /c/dev/projects/elasticplay/elastic_kibana/data01:/usr/share/elasticsearch/data
    networks: [elastic]
    environment:
      - discovery.type=single-node
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: kibana1
      XPACK_SECURITY_ENCRYPTIONKEY: something_at_least_32_characters
    ports:
      - 5601:5601
    networks: [elastic]
networks:
  elastic:
  
